language: php

php:
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

script:
  - php artisan analise:file

deploy:
  local_dir: build
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master